// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace LinkopingWebApp
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Type")]
            public string Type { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Location")]
            public string Location { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Part of Linkoping")]
            public string Part_of_Linkoping { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Year Built")]
            public float Year_Built { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Rooms")]
            public float Rooms { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Living Area")]
            public float Living_Area { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Land Area")]
            public float Land_Area { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Type")]
            public float[] Type { get; set; }

            [ColumnName(@"Location")]
            public float[] Location { get; set; }

            [ColumnName(@"Part of Linkoping")]
            public float[] Part_of_Linkoping { get; set; }

            [ColumnName(@"Year Built")]
            public float Year_Built { get; set; }

            [ColumnName(@"Rooms")]
            public float Rooms { get; set; }

            [ColumnName(@"Living Area")]
            public float Living_Area { get; set; }

            [ColumnName(@"Land Area")]
            public float Land_Area { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
